def preparar_set():
    return [("Esto factura es una factura","factura"),
            ("texto de factura factura","factura"),
            ("la factura me factura mola","factura"),
            ("factura de la factura sardanya","factura"),
            ("facturame al oido factura","factura"),
            ("Esto albarán es una albarán","albarán"),
            ("texto albarán de albarán","albarán"),
            ("la albarán albarán me mola","albarán"),
            ("albarán de albarán la sardanya","albarán"),
            ("albarán al oido albarán","albarán"),
            ("Esto es una nota de gasto nota de gasto","nota de gasto"),
            ("texto de nota de gasto nota de gasto","nota de gasto"),
            ("la nota de gasto me mola","nota de gasto"),
            ("nota de gasto nota de gasto de la sardanya","nota de gasto"),
            ("nota de gasto nota de gasto al oido sss","nota de gasto"),
            ("Esto factura es una factura","factura"),
            ("texto de factura factura","factura"),
            ("la factura me factura mola","factura"),
            ("factura de la factura sardanya","factura"),
            ("facturame al oido factura","factura"),
            ("Esto albarán es una albarán","albarán"),
            ("texto albarán de albarán","albarán"),
            ("la albarán albarán me mola","albarán"),
            ("albarán de albarán la sardanya","albarán"),
            ("albarán al oido albarán","albarán"),
            ("Esto es una nota de gasto nota de gasto","nota de gasto"),
            ("texto de nota de gasto nota de gasto","nota de gasto"),
            ("la nota de gasto me mola","nota de gasto"),
            ("nota de gasto nota de gasto de la sardanya","nota de gasto"),
            ("nota de gasto nota de gasto al oido sss","nota de gasto"),
            ("Esto factura es una factura","factura"),
            ("texto de factura factura","factura"),
            ("la factura me factura mola","factura"),
            ("factura de la factura sardanya","factura"),
            ("facturame al oido factura","factura"),
            ("Esto albarán es una albarán","albarán"),
            ("texto albarán de albarán","albarán"),
            ("la albarán albarán me mola","albarán"),
            ("albarán de albarán la sardanya","albarán"),
            ("albarán al oido albarán","albarán"),
            ("Esto es una nota de gasto nota de gasto","nota de gasto"),
            ("texto de nota de gasto nota de gasto","nota de gasto"),
            ("la nota de gasto me mola","nota de gasto"),
            ("nota de gasto nota de gasto de la sardanya","nota de gasto"),
            ("nota de gasto nota de gasto al oido sss","nota de gasto"),
            ("Esto factura es una factura","factura"),
            ("texto de factura factura","factura"),
            ("la factura me factura mola","factura"),
            ("factura de la factura sardanya","factura"),
            ("facturame al oido factura","factura"),
            ("Esto albarán es una albarán","albarán"),
            ("texto albarán de albarán","albarán"),
            ("la albarán albarán me mola","albarán"),
            ("albarán de albarán la sardanya","albarán"),
            ("albarán al oido albarán","albarán"),
            ("Esto es una nota de gasto nota de gasto","nota de gasto"),
            ("texto de nota de gasto nota de gasto","nota de gasto"),
            ("la nota de gasto me mola","nota de gasto"),
            ("nota de gasto nota de gasto de la sardanya","nota de gasto"),
            ("nota de gasto nota de gasto al oido sss","nota de gasto"),
            ]